
CONNECTOR_KAPITONOV_M1 = 'KAPITONOV-M1-RS485'
CONNECTOR_OWENCLOUD_GATEWAY = 'OWENCLOUD-GATEWAY'

CONNECTORS = {
   (CONNECTOR_KAPITONOV_M1, 'Модем "Капитонов М1-RS485". Протокол Modbus'),   
   (CONNECTOR_OWENCLOUD_GATEWAY, 'OwenCloud API Gateway'),      
}
