CONNECTOR_REST_API_1 = 'REST-API-1'
CONNECTOR_MQTT_1 = 'MQTT-1'
CONNECTOR_OWENCLOUD_GATEWAY = 'OWENCLOUD-GATEWAY'

CONNECTORS = [
   (CONNECTOR_REST_API_1,        'REST API v1'),   
   (CONNECTOR_MQTT_1,            'MQTT API v1'),   
   (CONNECTOR_OWENCLOUD_GATEWAY, 'OwenCloud API Gateway'),      
]
