# Generated by Django 4.1 on 2022-08-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование устройства')),
                ('polling_period', models.PositiveSmallIntegerField(default=30, verbose_name='Период опроса устройства, сек')),
                ('timeout', models.PositiveSmallIntegerField(default=600, verbose_name='Таймайут потери связи с устройством, сек')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего обновления данных')),
                ('connector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectors.connector', verbose_name='Коннектор')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
            },
        ),
        migrations.CreateModel(
            name='DeviceProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(choices=[('MODBUS-RTU', 'MODBUS-RTU'), ('MODBUS-ASCII', 'MODBUS-ASCII'), ('MODBUS-TCP', 'MODBUS-TCP')], default='MODBUS-RTU', max_length=20, verbose_name='Протокол')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name': 'Параметры связи с устройством',
                'verbose_name_plural': 'Параметры связи с устройством',
            },
        ),
        migrations.CreateModel(
            name='ModbusTcpProtocolParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.PositiveSmallIntegerField(default=1, verbose_name='IP-адрес устройства')),
                ('packet_timout', models.PositiveSmallIntegerField(default=300, verbose_name='Таймаут соединения, мс')),
                ('allow_group_reading', models.BooleanField(default=True, verbose_name='Разрешить груповое чтение')),
                ('lower_byte_forward', models.BooleanField(default=True)),
                ('lower_register_forward', models.BooleanField(default=False)),
                ('protocol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceprotocol')),
            ],
            options={
                'verbose_name': 'Параметры Modbus-TCP',
                'verbose_name_plural': 'Параметры Modbus-TCP',
            },
        ),
        migrations.CreateModel(
            name='ModbusRtuProtocolParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.PositiveSmallIntegerField(default=1, verbose_name='Адрес устройства')),
                ('baudrate', models.PositiveIntegerField(choices=[(300, '300'), (600, '600'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (28800, '28800'), (38400, '38400'), (57600, '57600'), (115200, '115200')], default=9600, verbose_name='Скорость обмена данными')),
                ('address_size', models.CharField(choices=[('8', '8')], default='8', max_length=1, verbose_name='Длинна адреса')),
                ('parity', models.CharField(choices=[('none', 'none'), ('odd', 'odd'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности')),
                ('stopbit', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1, verbose_name='Стоп бит')),
                ('bit_timout', models.PositiveSmallIntegerField(default=100, verbose_name='Таймаут бита, мс')),
                ('packet_timout', models.PositiveSmallIntegerField(default=300, verbose_name='Таймаут соединения, мс')),
                ('allow_group_reading', models.BooleanField(default=True, verbose_name='Разрешить груповое чтение')),
                ('lower_byte_forward', models.BooleanField(default=True)),
                ('lower_register_forward', models.BooleanField(default=False)),
                ('protocol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceprotocol')),
            ],
            options={
                'verbose_name': 'Параметры Modbus-RTU',
                'verbose_name_plural': 'Параметры Modbus-RTU',
            },
        ),
        migrations.CreateModel(
            name='ModbusAsciiProtocolParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.PositiveSmallIntegerField(default=1, verbose_name='Адрес устройства')),
                ('baudrate', models.PositiveIntegerField(choices=[(300, '300'), (600, '600'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (28800, '28800'), (38400, '38400'), (57600, '57600'), (115200, '115200')], default=9600, verbose_name='Скорость обмена данными')),
                ('address_size', models.CharField(choices=[('8', '8')], default='8', max_length=1, verbose_name='Длинна адреса')),
                ('parity', models.CharField(choices=[('none', 'none'), ('odd', 'odd'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности')),
                ('stopbit', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1, verbose_name='Стоп бит')),
                ('bit_timout', models.PositiveSmallIntegerField(default=100, verbose_name='Таймаут бита, мс')),
                ('packet_timout', models.PositiveSmallIntegerField(default=300, verbose_name='Таймаут соединения, мс')),
                ('allow_group_reading', models.BooleanField(default=True, verbose_name='Разрешить груповое чтение')),
                ('lower_byte_forward', models.BooleanField(default=True)),
                ('lower_register_forward', models.BooleanField(default=False)),
                ('protocol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceprotocol')),
            ],
            options={
                'verbose_name': 'Параметры Modbus-ASCII',
                'verbose_name_plural': 'Параметры Modbus-ASCII',
            },
        ),
    ]
