# Generated by Django 3.1.1 on 2020-10-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(14400, '14400'), (4800, '4800'), (300, '300'), (38400, '38400'), (2400, '2400'), (115200, '115200'), (19200, '19200'), (9600, '9600'), (600, '600'), (57600, '57600'), (1200, '1200'), (28800, '28800')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('odd', 'odd'), ('even', 'even'), ('none', 'none')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('BOOL', 'BOOL'), ('STRING', 'STRING'), ('INT', 'INT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
