# Generated by Django 4.0.6 on 2022-08-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_type', models.CharField(choices=[('MODBUS-RTU', 'MODBUS-RTU'), ('MODBUS-ASCII', 'MODBUS-ASCII'), ('MODBUS-TCP', 'MODBUS-TCP')], default='MODBUS-RTU', max_length=20, verbose_name='Протокол')),
            ],
            options={
                'verbose_name': 'Параметры связи с устройством',
                'verbose_name_plural': 'Параметры связи с устройством',
            },
        ),
        migrations.CreateModel(
            name='ModbusAsciiProtocolParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.PositiveSmallIntegerField(default=1, verbose_name='Адрес устройства')),
                ('baudrate', models.PositiveIntegerField(choices=[(300, '300'), (600, '600'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (28800, '28800'), (38400, '38400'), (57600, '57600'), (115200, '115200')], default=9600, verbose_name='Скорость обмена данными')),
                ('address_size', models.CharField(choices=[('8', '8')], default='8', max_length=1, verbose_name='Длинна адреса')),
                ('parity', models.CharField(choices=[('none', 'none'), ('odd', 'odd'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности')),
                ('stopbit', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1, verbose_name='Стоп бит')),
                ('bit_timout', models.PositiveSmallIntegerField(default=100, verbose_name='Таймаут бита, мс')),
                ('packet_timout', models.PositiveSmallIntegerField(default=300, verbose_name='Таймаут соединения, мс')),
                ('allow_group_reading', models.BooleanField(default=True, verbose_name='Разрешить груповое чтение')),
                ('lower_byte_forward', models.BooleanField(default=True)),
                ('lower_register_forward', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Параметры Modbus-ASCII',
                'verbose_name_plural': 'Параметры Modbus-ASCII',
            },
        ),
        migrations.CreateModel(
            name='ModbusRtuProtocolParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_address', models.PositiveSmallIntegerField(default=1, verbose_name='Адрес устройства')),
                ('baudrate', models.PositiveIntegerField(choices=[(300, '300'), (600, '600'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (28800, '28800'), (38400, '38400'), (57600, '57600'), (115200, '115200')], default=9600, verbose_name='Скорость обмена данными')),
                ('address_size', models.CharField(choices=[('8', '8')], default='8', max_length=1, verbose_name='Длинна адреса')),
                ('parity', models.CharField(choices=[('none', 'none'), ('odd', 'odd'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности')),
                ('stopbit', models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1, verbose_name='Стоп бит')),
                ('bit_timout', models.PositiveSmallIntegerField(default=100, verbose_name='Таймаут бита, мс')),
                ('packet_timout', models.PositiveSmallIntegerField(default=300, verbose_name='Таймаут соединения, мс')),
                ('allow_group_reading', models.BooleanField(default=True, verbose_name='Разрешить груповое чтение')),
                ('lower_byte_forward', models.BooleanField(default=True)),
                ('lower_register_forward', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Параметры Modbus-RTU',
                'verbose_name_plural': 'Параметры Modbus-RTU',
            },
        ),
        migrations.CreateModel(
            name='ModbusTcpProtocolParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_ip', models.PositiveSmallIntegerField(default=1, verbose_name='IP-адрес устройства')),
                ('packet_timout', models.PositiveSmallIntegerField(default=300, verbose_name='Таймаут соединения, мс')),
                ('allow_group_reading', models.BooleanField(default=True, verbose_name='Разрешить груповое чтение')),
                ('lower_byte_forward', models.BooleanField(default=True)),
                ('lower_register_forward', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Параметры Modbus-TCP',
                'verbose_name_plural': 'Параметры Modbus-TCP',
            },
        ),
        migrations.RemoveField(
            model_name='currentbooleanvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='currentfloatvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='currentintvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='currentstringvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalbooleanvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalfloatvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalintvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalstringvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='modbusdeviceparameters',
            name='device',
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tag',
            name='device',
        ),
        migrations.RemoveField(
            model_name='modbustagparameters',
            name='data_type',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
