# Generated by Django 4.1 on 2022-08-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modbusasciiprotocolparameters',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='modbusrtuprotocolparameters',
            name='protocol',
        ),
        migrations.RemoveField(
            model_name='modbustcpprotocolparameters',
            name='protocol',
        ),
        migrations.AddField(
            model_name='device',
            name='protocol_mb_ascii',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.modbusasciiprotocolparameters'),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol_mb_rtu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.modbusrtuprotocolparameters'),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol_mb_tcp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.modbustcpprotocolparameters'),
        ),
        migrations.AddField(
            model_name='device',
            name='protocol_type',
            field=models.CharField(choices=[('MODBUS-RTU', 'MODBUS-RTU'), ('MODBUS-ASCII', 'MODBUS-ASCII'), ('MODBUS-TCP', 'MODBUS-TCP')], default='MODBUS-RTU', max_length=20, verbose_name='Протокол'),
        ),
        migrations.DeleteModel(
            name='DeviceProtocol',
        ),
    ]
