# Generated by Django 3.1.1 on 2020-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20201013_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connector_type',
            field=models.CharField(choices=[('OWENCLOUD-GATEWAY', 'OwenCloud API Gateway'), ('KAPITONOV-M1-RS485', 'Модем "Капитонов М1-RS485". Протокол Modbus')], max_length=20, verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(115200, '115200'), (28800, '28800'), (1200, '1200'), (600, '600'), (300, '300'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (57600, '57600'), (38400, '38400')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('even', 'even'), ('none', 'none'), ('odd', 'odd')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('INT', 'INT'), ('BOOL', 'BOOL'), ('FLOAT', 'FLOAT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
