# Generated by Django 3.1.1 on 2020-10-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20201012_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='code',
            field=models.CharField(default='code', max_length=40, unique=True, verbose_name='Код'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='name', max_length=100, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(19200, '19200'), (2400, '2400'), (38400, '38400'), (4800, '4800'), (28800, '28800'), (14400, '14400'), (600, '600'), (9600, '9600'), (1200, '1200'), (300, '300'), (115200, '115200'), (57600, '57600')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('even', 'even'), ('odd', 'odd'), ('none', 'none')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('ASCII', 'MODBUS-ASCII'), ('TCP', 'MODBUS-TCP')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
    ]
