# Generated by Django 4.0.6 on 2022-08-09 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_deviceprotocol_modbusasciiprotocolparameters_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentBooleanValue',
        ),
        migrations.DeleteModel(
            name='CurrentFloatValue',
        ),
        migrations.DeleteModel(
            name='CurrentIntValue',
        ),
        migrations.DeleteModel(
            name='CurrentStringValue',
        ),
        migrations.DeleteModel(
            name='HistoricalBooleanValue',
        ),
        migrations.DeleteModel(
            name='HistoricalFloatValue',
        ),
        migrations.DeleteModel(
            name='HistoricalIntValue',
        ),
        migrations.DeleteModel(
            name='HistoricalStringValue',
        ),
        migrations.DeleteModel(
            name='ModbusDeviceParameters',
        ),
        migrations.AddField(
            model_name='deviceprotocol',
            name='device',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modbusasciiprotocolparameters',
            name='protocol',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.deviceprotocol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modbusrtuprotocolparameters',
            name='protocol',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.deviceprotocol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modbustcpprotocolparameters',
            name='protocol',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.deviceprotocol'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ModbusTagParameters',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
