# Generated by Django 4.1 on 2022-08-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_modbusasciiprotocolparameters_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbustcpprotocolparameters',
            name='device_ip',
            field=models.CharField(default='127.0.0.1', max_length=16, verbose_name='IP-адрес устройства'),
        ),
    ]
