# Generated by Django 3.1.1 on 2020-10-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20201013_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connector_type',
            field=models.CharField(choices=[('KAPITONOV-M1-RS485', 'Модем "Капитонов М1-RS485". Протокол Modbus'), ('OWENCLOUD-GATEWAY', 'OwenCloud API Gateway')], max_length=20, verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(115200, '115200'), (600, '600'), (9600, '9600'), (4800, '4800'), (38400, '38400'), (2400, '2400'), (57600, '57600'), (1200, '1200'), (14400, '14400'), (19200, '19200'), (300, '300'), (28800, '28800')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('ASCII', 'MODBUS-ASCII'), ('TCP', 'MODBUS-TCP')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('STRING', 'STRING'), ('INT', 'INT'), ('FLOAT', 'FLOAT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
