# Generated by Django 3.1.1 on 2020-10-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_auto_20201013_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(28800, '28800'), (19200, '19200'), (2400, '2400'), (600, '600'), (300, '300'), (9600, '9600'), (4800, '4800'), (57600, '57600'), (38400, '38400'), (1200, '1200'), (14400, '14400'), (115200, '115200')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('ASCII', 'MODBUS-ASCII'), ('TCP', 'MODBUS-TCP')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('WORD', 'WORD'), ('INT', 'INT'), ('BOOL', 'BOOL'), ('UINT', 'UINT'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('BOOL', 'BOOL'), ('STRING', 'STRING'), ('INT', 'INT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
