# Generated by Django 3.1.1 on 2020-10-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20201012_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(300, '300'), (38400, '38400'), (4800, '4800'), (57600, '57600'), (115200, '115200'), (14400, '14400'), (28800, '28800'), (9600, '9600'), (19200, '19200'), (2400, '2400'), (1200, '1200'), (600, '600')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='device_address',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Адрес устройства'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('even', 'even'), ('none', 'none'), ('odd', 'odd')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
    ]
