# Generated by Django 3.1.1 on 2020-11-05 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20201015_1015'),
        ('devices', '0004_auto_20201014_0941'),
    ]

    operations = [
    ]
