# Generated by Django 3.1.1 on 2020-10-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20201012_1819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FloatValue',
            new_name='CurrentFloatValue',
        ),
        migrations.RenameModel(
            old_name='IntValue',
            new_name='CurrentIntValue',
        ),
        migrations.RenameModel(
            old_name='StringValue',
            new_name='CurrentStringValue',
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(2400, '2400'), (9600, '9600'), (300, '300'), (38400, '38400'), (1200, '1200'), (4800, '4800'), (28800, '28800'), (14400, '14400'), (57600, '57600'), (19200, '19200'), (115200, '115200'), (600, '600')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('even', 'even'), ('odd', 'odd'), ('none', 'none')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
    ]
