# Generated by Django 3.1.1 on 2020-11-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_merge_20201105_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modbustagparameters',
            name='lower_byte_forward',
        ),
        migrations.RemoveField(
            model_name='modbustagparameters',
            name='lower_register_forward',
        ),
        migrations.AddField(
            model_name='modbusdeviceparameters',
            name='lower_byte_forward',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modbusdeviceparameters',
            name='lower_register_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(14400, '14400'), (38400, '38400'), (115200, '115200'), (9600, '9600'), (1200, '1200'), (19200, '19200'), (4800, '4800'), (28800, '28800'), (300, '300'), (2400, '2400'), (57600, '57600'), (600, '600')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('odd', 'odd'), ('none', 'none'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('UINT', 'UINT'), ('STRING', 'STRING'), ('WORD', 'WORD'), ('FLOAT', 'FLOAT'), ('INT', 'INT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('INT', 'INT'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('BOOL', 'BOOL')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
