# Generated by Django 3.1.1 on 2020-10-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20201012_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('BOOL', 'BOOL'), ('INT', 'INT'), ('FLOAT', 'FLOAT')], default=1, max_length=20, verbose_name='Тип данных'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(38400, '38400'), (600, '600'), (57600, '57600'), (9600, '9600'), (1200, '1200'), (14400, '14400'), (19200, '19200'), (28800, '28800'), (300, '300'), (4800, '4800'), (115200, '115200'), (2400, '2400')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('ASCII', 'MODBUS-ASCII'), ('RTU', 'MODBUS-RTU'), ('TCP', 'MODBUS-TCP')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
    ]
