# Generated by Django 3.1.1 on 2020-11-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_auto_20201106_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connector_type',
            field=models.CharField(choices=[('OWENCLOUD-GATEWAY', 'OwenCloud API Gateway'), ('KAPITONOV-M1-RS485', 'Модем "Капитонов М1-RS485". Протокол Modbus')], max_length=20, verbose_name='Тип подключения'),
        ),
        migrations.AlterField(
            model_name='historicalbooleanvalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.tag'),
        ),
        migrations.AlterField(
            model_name='historicalfloatvalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.tag'),
        ),
        migrations.AlterField(
            model_name='historicalintvalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.tag'),
        ),
        migrations.AlterField(
            model_name='historicalstringvalue',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.tag'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(38400, '38400'), (2400, '2400'), (9600, '9600'), (300, '300'), (1200, '1200'), (14400, '14400'), (115200, '115200'), (19200, '19200'), (4800, '4800'), (57600, '57600'), (28800, '28800'), (600, '600')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('odd', 'odd'), ('even', 'even'), ('none', 'none')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('ASCII', 'MODBUS-ASCII'), ('RTU', 'MODBUS-RTU'), ('TCP', 'MODBUS-TCP')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('UINT', 'UINT'), ('FLOAT', 'FLOAT'), ('WORD', 'WORD'), ('STRING', 'STRING'), ('INT', 'INT'), ('BOOL', 'BOOL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('FLOAT', 'FLOAT'), ('BOOL', 'BOOL'), ('INT', 'INT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
