# Generated by Django 3.1.1 on 2020-11-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
        ('devices', '0008_auto_20201106_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='connector_type',
        ),
        migrations.AddField(
            model_name='device',
            name='connector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connectors.connector', verbose_name='Коннектор'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(300, '300'), (2400, '2400'), (115200, '115200'), (1200, '1200'), (38400, '38400'), (600, '600'), (4800, '4800'), (19200, '19200'), (9600, '9600'), (57600, '57600'), (28800, '28800'), (14400, '14400')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('odd', 'odd'), ('none', 'none'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('TCP', 'MODBUS-TCP'), ('ASCII', 'MODBUS-ASCII'), ('RTU', 'MODBUS-RTU')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('INT', 'INT'), ('FLOAT', 'FLOAT'), ('BOOL', 'BOOL'), ('STRING', 'STRING'), ('WORD', 'WORD'), ('UINT', 'UINT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('INT', 'INT'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
