# Generated by Django 3.1.1 on 2020-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_auto_20201123_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(28800, '28800'), (600, '600'), (9600, '9600'), (115200, '115200'), (2400, '2400'), (1200, '1200'), (38400, '38400'), (300, '300'), (57600, '57600'), (14400, '14400'), (4800, '4800'), (19200, '19200')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('odd', 'odd'), ('none', 'none'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('WORD', 'WORD'), ('INT', 'INT'), ('BOOL', 'BOOL'), ('FLOAT', 'FLOAT'), ('UINT', 'UINT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('BOOL', 'BOOL'), ('INT', 'INT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
