# Generated by Django 3.1.1 on 2020-11-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_name'),
        ('devices', '0016_auto_20201123_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility', verbose_name='Объект'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(1200, '1200'), (4800, '4800'), (2400, '2400'), (9600, '9600'), (28800, '28800'), (57600, '57600'), (38400, '38400'), (300, '300'), (115200, '115200'), (600, '600'), (14400, '14400'), (19200, '19200')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('even', 'even'), ('none', 'none'), ('odd', 'odd')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('INT', 'INT'), ('BOOL', 'BOOL'), ('WORD', 'WORD'), ('UINT', 'UINT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('STRING', 'STRING'), ('INT', 'INT'), ('FLOAT', 'FLOAT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
