# Generated by Django 3.1.1 on 2020-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0021_auto_20201212_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='display_on_graph_by_default',
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(2400, '2400'), (4800, '4800'), (600, '600'), (38400, '38400'), (1200, '1200'), (28800, '28800'), (300, '300'), (9600, '9600'), (19200, '19200'), (14400, '14400'), (57600, '57600'), (115200, '115200')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('ASCII', 'MODBUS-ASCII'), ('TCP', 'MODBUS-TCP')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('WORD', 'WORD'), ('BOOL', 'BOOL'), ('UINT', 'UINT'), ('STRING', 'STRING'), ('INT', 'INT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('FLOAT', 'FLOAT'), ('INT', 'INT'), ('STRING', 'STRING')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
