# Generated by Django 3.1.1 on 2021-01-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0022_auto_20201215_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(600, '600'), (9600, '9600'), (115200, '115200'), (28800, '28800'), (57600, '57600'), (4800, '4800'), (14400, '14400'), (2400, '2400'), (38400, '38400'), (300, '300'), (1200, '1200'), (19200, '19200')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('even', 'even'), ('odd', 'odd'), ('none', 'none')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('TCP', 'MODBUS-TCP'), ('ASCII', 'MODBUS-ASCII')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('WORD', 'WORD'), ('INT', 'INT'), ('STRING', 'STRING'), ('UINT', 'UINT'), ('BOOL', 'BOOL'), ('FLOAT', 'FLOAT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('FLOAT', 'FLOAT'), ('BOOL', 'BOOL'), ('INT', 'INT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
