# Generated by Django 3.1.1 on 2021-01-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0023_auto_20210115_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(300, '300'), (9600, '9600'), (38400, '38400'), (14400, '14400'), (4800, '4800'), (2400, '2400'), (28800, '28800'), (1200, '1200'), (19200, '19200'), (600, '600'), (57600, '57600'), (115200, '115200')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('UINT', 'UINT'), ('WORD', 'WORD'), ('BOOL', 'BOOL'), ('INT', 'INT'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('BOOL', 'BOOL'), ('FLOAT', 'FLOAT'), ('INT', 'INT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
