# Generated by Django 3.1.1 on 2021-01-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0028_auto_20210122_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(600, '600'), (9600, '9600'), (28800, '28800'), (2400, '2400'), (4800, '4800'), (300, '300'), (1200, '1200'), (38400, '38400'), (19200, '19200'), (14400, '14400'), (115200, '115200'), (57600, '57600')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('TCP', 'MODBUS-TCP'), ('ASCII', 'MODBUS-ASCII')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('WORD', 'WORD'), ('INT', 'INT'), ('UINT', 'UINT'), ('STRING', 'STRING'), ('FLOAT', 'FLOAT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('FLOAT', 'FLOAT'), ('BOOL', 'BOOL'), ('INT', 'INT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
