# Generated by Django 3.1.1 on 2021-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0031_auto_20210122_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(57600, '57600'), (300, '300'), (1200, '1200'), (38400, '38400'), (600, '600'), (4800, '4800'), (28800, '28800'), (9600, '9600'), (19200, '19200'), (115200, '115200'), (14400, '14400'), (2400, '2400')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('odd', 'odd'), ('even', 'even'), ('none', 'none')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('TCP', 'MODBUS-TCP'), ('ASCII', 'MODBUS-ASCII'), ('RTU', 'MODBUS-RTU')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('UINT', 'UINT'), ('BOOL', 'BOOL'), ('STRING', 'STRING'), ('WORD', 'WORD'), ('INT', 'INT'), ('FLOAT', 'FLOAT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('INT', 'INT'), ('FLOAT', 'FLOAT'), ('BOOL', 'BOOL')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
