# Generated by Django 3.1.1 on 2021-01-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0032_auto_20210122_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(9600, '9600'), (4800, '4800'), (57600, '57600'), (14400, '14400'), (28800, '28800'), (115200, '115200'), (1200, '1200'), (600, '600'), (19200, '19200'), (38400, '38400'), (300, '300'), (2400, '2400')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('TCP', 'MODBUS-TCP'), ('RTU', 'MODBUS-RTU'), ('ASCII', 'MODBUS-ASCII')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('BOOL', 'BOOL'), ('UINT', 'UINT'), ('INT', 'INT'), ('WORD', 'WORD'), ('STRING', 'STRING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('BOOL', 'BOOL'), ('INT', 'INT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
