# Generated by Django 3.1.1 on 2021-02-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0035_auto_20210201_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(300, '300'), (9600, '9600'), (57600, '57600'), (115200, '115200'), (2400, '2400'), (4800, '4800'), (19200, '19200'), (28800, '28800'), (1200, '1200'), (14400, '14400'), (600, '600'), (38400, '38400')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('ASCII', 'MODBUS-ASCII'), ('TCP', 'MODBUS-TCP'), ('RTU', 'MODBUS-RTU')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('INT', 'INT'), ('BOOL', 'BOOL'), ('UINT', 'UINT'), ('FLOAT', 'FLOAT'), ('WORD', 'WORD'), ('STRING', 'STRING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('STRING', 'STRING'), ('INT', 'INT'), ('FLOAT', 'FLOAT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
