# Generated by Django 3.1.1 on 2021-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0037_auto_20210201_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(115200, '115200'), (2400, '2400'), (9600, '9600'), (57600, '57600'), (4800, '4800'), (300, '300'), (38400, '38400'), (14400, '14400'), (1200, '1200'), (28800, '28800'), (19200, '19200'), (600, '600')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('even', 'even'), ('odd', 'odd'), ('none', 'none')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('TCP', 'MODBUS-TCP'), ('ASCII', 'MODBUS-ASCII'), ('RTU', 'MODBUS-RTU')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('INT', 'INT'), ('STRING', 'STRING'), ('FLOAT', 'FLOAT'), ('WORD', 'WORD'), ('BOOL', 'BOOL'), ('UINT', 'UINT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('INT', 'INT'), ('STRING', 'STRING'), ('BOOL', 'BOOL')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
