# Generated by Django 3.1.1 on 2021-02-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0038_auto_20210201_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(9600, '9600'), (38400, '38400'), (600, '600'), (14400, '14400'), (19200, '19200'), (115200, '115200'), (57600, '57600'), (1200, '1200'), (300, '300'), (4800, '4800'), (28800, '28800'), (2400, '2400')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('odd', 'odd'), ('none', 'none'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('FLOAT', 'FLOAT'), ('INT', 'INT'), ('UINT', 'UINT'), ('WORD', 'WORD'), ('BOOL', 'BOOL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(max_length=40, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('INT', 'INT'), ('BOOL', 'BOOL'), ('FLOAT', 'FLOAT')], max_length=20, verbose_name='Тип данных'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('code', 'device')},
        ),
    ]
