# Generated by Django 3.1.7 on 2021-02-20 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0039_auto_20210219_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='boudrate',
            field=models.PositiveSmallIntegerField(choices=[(600, '600'), (2400, '2400'), (4800, '4800'), (14400, '14400'), (57600, '57600'), (300, '300'), (19200, '19200'), (1200, '1200'), (28800, '28800'), (115200, '115200'), (9600, '9600'), (38400, '38400')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('even', 'even'), ('odd', 'odd'), ('none', 'none')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('UINT', 'UINT'), ('WORD', 'WORD'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('INT', 'INT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('BOOL', 'BOOL'), ('STRING', 'STRING'), ('INT', 'INT'), ('FLOAT', 'FLOAT')], max_length=20, verbose_name='Тип данных'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Устройство'),
        ),
    ]
