# Generated by Django 3.1.7 on 2021-02-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0041_auto_20210220_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modbusdeviceparameters',
            name='boudrate',
        ),
        migrations.AddField(
            model_name='modbusdeviceparameters',
            name='baudrate',
            field=models.PositiveSmallIntegerField(choices=[(300, '300'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (115200, '115200'), (9600, '9600'), (57600, '57600'), (38400, '38400'), (28800, '28800'), (14400, '14400'), (600, '600'), (19200, '19200')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('none', 'none'), ('odd', 'odd'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('ASCII', 'MODBUS-ASCII'), ('TCP', 'MODBUS-TCP')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('FLOAT', 'FLOAT'), ('INT', 'INT'), ('BOOL', 'BOOL'), ('STRING', 'STRING'), ('UINT', 'UINT'), ('WORD', 'WORD')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('FLOAT', 'FLOAT'), ('INT', 'INT'), ('BOOL', 'BOOL')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
