# Generated by Django 3.1.7 on 2021-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0043_auto_20210227_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='baudrate',
            field=models.PositiveIntegerField(choices=[(300, '300'), (600, '600'), (1200, '1200'), (2400, '2400'), (4800, '4800'), (9600, '9600'), (14400, '14400'), (19200, '19200'), (28800, '28800'), (38400, '38400'), (57600, '57600'), (115200, '115200')], default=9600, verbose_name='Скорость обмена данными'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('none', 'none'), ('even', 'even'), ('odd', 'odd')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('TCP', 'MODBUS-TCP'), ('ASCII', 'MODBUS-ASCII')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('WORD', 'WORD'), ('INT', 'INT'), ('STRING', 'STRING'), ('BOOL', 'BOOL'), ('UINT', 'UINT'), ('FLOAT', 'FLOAT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'STRING'), ('INT', 'INT'), ('BOOL', 'BOOL'), ('FLOAT', 'FLOAT')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
