# Generated by Django 3.1.7 on 2021-02-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0044_auto_20210227_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='parity',
            field=models.CharField(choices=[('none', 'none'), ('odd', 'odd'), ('even', 'even')], default='none', max_length=4, verbose_name='Контроль четности'),
        ),
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='protocol_type',
            field=models.CharField(choices=[('RTU', 'MODBUS-RTU'), ('ASCII', 'MODBUS-ASCII'), ('TCP', 'MODBUS-TCP')], default='RTU', max_length=5, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='modbustagparameters',
            name='data_type',
            field=models.CharField(choices=[('WORD', 'WORD'), ('INT', 'INT'), ('UINT', 'UINT'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('BOOL', 'BOOL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data_type',
            field=models.CharField(choices=[('INT', 'INT'), ('FLOAT', 'FLOAT'), ('STRING', 'STRING'), ('BOOL', 'BOOL')], max_length=20, verbose_name='Тип данных'),
        ),
    ]
