# Generated by Django 3.1.7 on 2021-02-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0045_auto_20210227_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modbusdeviceparameters',
            name='allow_group_reading',
            field=models.BooleanField(default=True, verbose_name='Разрешить груповое чтение'),
        ),
    ]
