# Generated by Django 4.0.6 on 2022-08-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusTagParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_address', models.PositiveSmallIntegerField()),
                ('read_function', models.CharField(choices=[('1', '1 - Read Coil'), ('2', '2 - Read Discrete Input'), ('3', '3 - Read Holding Registers'), ('4', '4 - Read Input Registers')], default='4', max_length=2)),
                ('write_function', models.CharField(choices=[('5', '5 - Write Single Coil'), ('6', '6 - Write Single Holding Register'), ('15', '15 - Write Multiple Coils'), ('16', '16 - Write Multiple Holding Registers')], default='16', max_length=2)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tags.tag')),
            ],
            options={
                'verbose_name': 'Параметры регистра модбас',
                'verbose_name_plural': 'Параметры регистров модбас',
            },
        ),
    ]
