# Generated by Django 4.1 on 2022-08-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True, verbose_name='Токен')),
                ('connector_type', models.CharField(choices=[('REST-API-1', 'REST API v1'), ('MQTT-1', 'MQTT API v1'), ('OWENCLOUD-GATEWAY', 'OwenCloud API Gateway')], max_length=20, verbose_name='Тип подключения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('registration_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Код регистрации')),
            ],
            options={
                'verbose_name': 'Коннектор',
                'verbose_name_plural': 'Коннекторы',
            },
        ),
    ]
