# Generated by Django 3.1.1 on 2020-11-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True, verbose_name='Токен')),
                ('connector_type', models.CharField(choices=[('OWENCLOUD-GATEWAY', 'OwenCloud API Gateway'), ('KAPITONOV-M1-RS485', 'Модем "Капитонов М1-RS485". Протокол Modbus')], max_length=20, verbose_name='Тип подключения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('registration_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Код регистрации')),
            ],
            options={
                'verbose_name': 'Коннектор',
                'verbose_name_plural': 'Коннекторы',
            },
        ),
    ]
