# Generated by Django 4.1 on 2022-08-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего сеанса связи'),
        ),
    ]
