# Generated by Django 3.1.1 on 2021-01-15 15:13

from django.db import migrations, models
import widgets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.JSONField(default=widgets.models.get_default_template, verbose_name='Шаблон виджетов')),
            ],
        ),
    ]
