# Generated by Django 4.1 on 2022-08-10 06:15

from django.db import migrations, models
import django.db.models.deletion
import widgets.default_template


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.JSONField(default=widgets.default_template.get_default_template, verbose_name='Шаблон виджетов')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Шаблон виджетов',
                'verbose_name_plural': 'Шаблоны виджетов',
            },
        ),
    ]
