# Generated by Django 3.1.1 on 2021-01-22 13:43

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0028_auto_20210122_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Журнал событий',
                'verbose_name_plural': 'Журналы событий',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(blank=True, verbose_name='Время и дата записи')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventslogs.log', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None, verbose_name='Категории')),
                ('expression', models.TextField(default='', verbose_name='Формула')),
                ('raise_message', models.TextField(default='', verbose_name='Сообщение срабатывания')),
                ('fall_message', models.TextField(default='', verbose_name='Сообщение отключения')),
                ('is_alarm', models.BooleanField(default=False, verbose_name='Событие аварийное')),
                ('is_active', models.BooleanField(default=False, verbose_name='Событие активно')),
                ('raise_time', models.DateTimeField(auto_now_add=True, verbose_name='Время возникновения')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
