# Generated by Django 4.0.6 on 2022-07-30 07:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Журнал событий',
                'verbose_name_plural': 'Журналы событий',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='-', verbose_name='Сообщение')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Время и дата записи')),
                ('category', models.CharField(choices=[('Alarm', 'Аварйное'), ('Warning', 'Предупреждение'), ('Info', 'Информационное'), ('Debug', 'Отладочное')], max_length=20, verbose_name='Категория')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventslogs.log', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Записи журналов',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Alarm', 'Аварйное'), ('Warning', 'Предупреждение'), ('Info', 'Информационное'), ('Debug', 'Отладочное')], default='Alarm', max_length=20, verbose_name='Категория')),
                ('enable', models.BooleanField(default=False, verbose_name='Активировать')),
                ('expression', models.TextField(verbose_name='Формула')),
                ('raise_message', models.TextField(verbose_name='Сообщение срабатывания')),
                ('fall_message', models.TextField(blank=True, verbose_name='Сообщение отключения')),
                ('is_alarm', models.BooleanField(default=False, verbose_name='Событие аварийное')),
                ('is_active', models.BooleanField(default=False, verbose_name='Событие активно')),
                ('raise_time', models.DateTimeField(blank=True, null=True, verbose_name='Время возникновения')),
                ('used_tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None, verbose_name='Используемые теги')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Устройство')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
