# Generated by Django 3.1.1 on 2021-01-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0003_auto_20210122_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='Активировать'),
        ),
        migrations.AlterField(
            model_name='event',
            name='expression',
            field=models.TextField(blank=True, verbose_name='Формула'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fall_message',
            field=models.TextField(blank=True, verbose_name='Сообщение отключения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='raise_message',
            field=models.TextField(blank=True, verbose_name='Сообщение срабатывания'),
        ),
        migrations.AlterField(
            model_name='record',
            name='message',
            field=models.TextField(default='-', verbose_name='Сообщение'),
        ),
    ]
