# Generated by Django 3.1.1 on 2021-01-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0004_auto_20210122_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись журнала', 'verbose_name_plural': 'Записи журналов'},
        ),
        migrations.AlterField(
            model_name='event',
            name='raise_time',
            field=models.DateTimeField(blank=True, verbose_name='Время возникновения'),
        ),
    ]
