# Generated by Django 3.1.1 on 2021-02-01 09:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0006_auto_20210122_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='used_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None, verbose_name='Используемые теги'),
            preserve_default=False,
        ),
    ]
