# Generated by Django 3.1.1 on 2021-02-01 09:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0009_auto_20210201_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='used_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None, verbose_name='Используемые теги'),
        ),
    ]
