# Generated by Django 3.1.1 on 2021-02-19 08:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0011_auto_20210201_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Отладочное', 'Отладочное'), ('Информационное', 'Информационное'), ('Предупреждение', 'Предупреждение'), ('Аварйное', 'Аварйное')], max_length=20), blank=True, default=list, size=None, verbose_name='Категории'),
        ),
    ]
