# Generated by Django 3.1.7 on 2021-02-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0012_auto_20210219_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Информационное', 'Информационное'), ('Предупреждение', 'Предупреждение'), ('Отладочное', 'Отладочное'), ('Аварйное', 'Аварйное')], default='Аварйное', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Информационное', 'Информационное'), ('Предупреждение', 'Предупреждение'), ('Отладочное', 'Отладочное'), ('Аварйное', 'Аварйное')], default='Аварйное', max_length=20, verbose_name='Категория'),
        ),
    ]
