# Generated by Django 3.1.7 on 2021-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0016_auto_20210227_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Info', 'Информационное'), ('Alarm', 'Аварйное'), ('Debug', 'Отладочное'), ('Warning', 'Предупреждение')], default='Alarm', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Info', 'Информационное'), ('Alarm', 'Аварйное'), ('Debug', 'Отладочное'), ('Warning', 'Предупреждение')], max_length=20, verbose_name='Категория'),
        ),
    ]
