# Generated by Django 3.1.7 on 2021-02-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0017_auto_20210227_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Alarm', 'Аварйное'), ('Warning', 'Предупреждение'), ('Info', 'Информационное'), ('Debug', 'Отладочное')], default='Alarm', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Alarm', 'Аварйное'), ('Warning', 'Предупреждение'), ('Info', 'Информационное'), ('Debug', 'Отладочное')], max_length=20, verbose_name='Категория'),
        ),
    ]
