# Generated by Django 3.1.7 on 2021-03-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0018_auto_20210227_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='raise_message',
            field=models.TextField(verbose_name='Сообщение срабатывания'),
        ),
    ]
