# Generated by Django 3.1.7 on 2021-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventslogs', '0019_auto_20210302_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='expression',
            field=models.TextField(verbose_name='Формула'),
        ),
    ]
