# Generated by Django 3.1.1 on 2020-11-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
    ]
